# Generated by Django 6.0 on 2025-12-23 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Event type in dot notation (e.g., user.created)",
                        max_length=100,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of the user who triggered the event",
                        null=True,
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of the organization context",
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Event payload data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="events_event_t_9f6b23_idx",
                    ),
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="events_user_id_3ca773_idx",
                    ),
                    models.Index(
                        fields=["organization_id", "created_at"],
                        name="events_organiz_a7b36d_idx",
                    ),
                ],
            },
        ),
    ]
