# Generated by Django 6.0 on 2025-12-23 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique idempotency key from request header",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "request_path",
                    models.CharField(help_text="API endpoint path", max_length=255),
                ),
                (
                    "request_method",
                    models.CharField(
                        help_text="HTTP method (POST, PUT, etc.)", max_length=10
                    ),
                ),
                (
                    "request_hash",
                    models.CharField(
                        help_text="SHA256 hash of request body for collision detection",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "response_status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="HTTP status code of the response",
                        null=True,
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(
                        blank=True,
                        help_text="Cached response body for replay",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this idempotency record expires (typically 24h)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Idempotency Record",
                "verbose_name_plural": "Idempotency Records",
                "db_table": "idempotency_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["key"], name="idempotency_key_84eb16_idx"),
                    models.Index(
                        fields=["expires_at"], name="idempotency_expires_79c374_idx"
                    ),
                    models.Index(
                        fields=["request_path", "request_method"],
                        name="idempotency_request_da265f_idx",
                    ),
                ],
            },
        ),
    ]
