# Generated by Django 6.0 on 2025-12-23 14:55

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.math
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("organizations", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable invoice number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "subtotal_cents",
                    models.BigIntegerField(help_text="Subtotal in cents before GST"),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0900"),
                        help_text="GST rate (default 9% = 0.0900)",
                        max_digits=5,
                    ),
                ),
                (
                    "gst_amount_cents",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.math.Round(
                            django.db.models.expressions.CombinedExpression(
                                models.F("subtotal_cents"), "*", models.F("gst_rate")
                            )
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "total_amount_cents",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("subtotal_cents"),
                            "+",
                            django.db.models.functions.math.Round(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("subtotal_cents"),
                                    "*",
                                    models.F("gst_rate"),
                                )
                            ),
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "iras_transaction_code",
                    models.CharField(
                        choices=[
                            ("SR", "Standard-Rated (9% GST)"),
                            ("ZR", "Zero-Rated"),
                            ("OS", "Out-of-Scope"),
                            ("TX", "Exempted"),
                        ],
                        default="SR",
                        help_text="IRAS transaction code for GST reporting",
                        max_length=2,
                    ),
                ),
                (
                    "amount_paid_cents",
                    models.BigIntegerField(default=0, help_text="Amount paid in cents"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SGD", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                            ("uncollectible", "Uncollectible"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(
                        default=False, help_text="Whether invoice is fully paid"
                    ),
                ),
                ("due_date", models.DateTimeField(help_text="Payment due date")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When invoice was fully paid", null=True
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        help_text="Stripe invoice ID", max_length=255, unique=True
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, help_text="Stripe payment intent ID", max_length=255
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(blank=True, help_text="URL to invoice PDF"),
                ),
                (
                    "line_items",
                    models.JSONField(
                        blank=True, default=list, help_text="Invoice line items"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this invoice belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related subscription (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="invoices_organiz_9b03bf_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="invoices_due_dat_039a25_idx"
                    ),
                    models.Index(
                        fields=["stripe_invoice_id"], name="invoices_stripe__83e0c8_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "amount_paid_cents__lte",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("subtotal_cents"),
                                    "+",
                                    django.db.models.functions.math.Round(
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("subtotal_cents"),
                                            "*",
                                            models.F("gst_rate"),
                                        )
                                    ),
                                ),
                            )
                        ),
                        name="amount_paid_not_exceed_total",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("paid", True), _negated=True),
                            ("paid_at__isnull", False),
                            _connector="OR",
                        ),
                        name="paid_invoices_require_paid_at",
                    ),
                ],
            },
        ),
    ]
