# Generated by Django 6.0 on 2025-12-23 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DSARRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email of the data subject",
                        max_length=254,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("export", "Data Export"),
                            ("delete", "Data Deletion"),
                            ("access", "Data Access"),
                            ("rectification", "Data Rectification"),
                        ],
                        db_index=True,
                        help_text="Type of DSAR request",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verifying", "Verifying"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Request status",
                        max_length=20,
                    ),
                ),
                (
                    "verification_token",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Token for email verification"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When email was verified", null=True
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        help_text="How verification was completed",
                        max_length=50,
                    ),
                ),
                (
                    "export_url",
                    models.URLField(
                        blank=True, help_text="URL to download data export"
                    ),
                ),
                (
                    "export_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When export link expires (7 days)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional request metadata",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, help_text="Reason for failure (if any)"
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing began", null=True
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When request was completed", null=True
                    ),
                ),
                (
                    "deletion_approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When deletion was approved", null=True
                    ),
                ),
                (
                    "deletion_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved deletion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_dsar_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated user account (if exists)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dsar_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DSAR Request",
                "verbose_name_plural": "DSAR Requests",
                "db_table": "dsar_requests",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["user_email", "status"],
                        name="dsar_reques_user_em_4c09ac_idx",
                    ),
                    models.Index(
                        fields=["requested_at"], name="dsar_reques_request_2a4529_idx"
                    ),
                    models.Index(
                        fields=["status", "requested_at"],
                        name="dsar_reques_status_62b399_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "completed"), _negated=True),
                            ("processed_at__isnull", False),
                            _connector="OR",
                        ),
                        name="completed_dsar_requires_processed_at",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("request_type", "delete"),
                                ("status", "completed"),
                                _negated=True,
                            ),
                            ("deletion_approved_by__isnull", False),
                            _connector="OR",
                        ),
                        name="deletion_requires_approval",
                    ),
                ],
            },
        ),
    ]
