# Generated by Django 6.0 on 2025-12-23 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Plan display name", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Plan description"),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Unique plan identifier", max_length=50, unique=True
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[("month", "Monthly"), ("year", "Yearly")],
                        default="month",
                        help_text="Billing cycle",
                        max_length=10,
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveIntegerField(
                        help_text="Price in cents (e.g., 2999 = $29.99)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SGD", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Feature flags (e.g., {"api_access": true})',
                    ),
                ),
                (
                    "limits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Usage limits (e.g., {"users": 10, "storage_gb": 50})',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether plan can be purchased"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Whether plan is shown on pricing page"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order on pricing page"
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True, help_text="Stripe product ID", max_length=255
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True, help_text="Stripe price ID", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "db_table": "plans",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                        ],
                        db_index=True,
                        default="trialing",
                        max_length=20,
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False, help_text="Whether to cancel at period end"
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(help_text="Start of current billing period"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(help_text="End of current billing period"),
                ),
                (
                    "trial_start",
                    models.DateTimeField(
                        blank=True, help_text="Trial start date", null=True
                    ),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True, help_text="Trial end date", null=True
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        help_text="Stripe subscription ID", max_length=255, unique=True
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(help_text="Stripe customer ID", max_length=255),
                ),
                (
                    "stripe_latest_invoice_id",
                    models.CharField(
                        blank=True, help_text="Latest Stripe invoice ID", max_length=255
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When subscription was canceled",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this subscription belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Subscribed plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="subscriptio_organiz_5780cf_idx"
                    ),
                    models.Index(
                        fields=["status", "organization"],
                        name="subscriptio_status_9fcbaa_idx",
                    ),
                    models.Index(
                        fields=["stripe_subscription_id"],
                        name="subscriptio_stripe__aa726e_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("current_period_end__gt", models.F("current_period_start"))
                        ),
                        name="period_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "trialing"), _negated=True),
                            ("trial_end__isnull", False),
                            _connector="OR",
                        ),
                        name="trial_status_requires_trial_end",
                    ),
                ],
            },
        ),
    ]
