# Generated by Django 6.0 on 2025-12-23 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        db_index=True,
                        help_text="Service name (e.g., stripe, sendgrid)",
                        max_length=50,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="External event ID from the service",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Event type (e.g., invoice.paid, customer.subscription.created)",
                        max_length=100,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Raw webhook payload from the service"),
                ),
                (
                    "processed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the event has been successfully processed",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of processing retry attempts"
                    ),
                ),
                (
                    "last_retry_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last retry attempt",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the event was successfully processed",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "db_table": "webhook_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["service", "event_type"],
                        name="webhook_eve_service_9be845_idx",
                    ),
                    models.Index(
                        fields=["processed", "created_at"],
                        name="webhook_eve_process_8c85e6_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="webhook_eve_created_8fa52f_idx"
                    ),
                ],
            },
        ),
    ]
