# Generated by Django 6.0 on 2025-12-23 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Lead name", max_length=255)),
                (
                    "email",
                    models.EmailField(
                        db_index=True, help_text="Lead email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20
                    ),
                ),
                ("company", models.CharField(help_text="Company name", max_length=255)),
                (
                    "job_title",
                    models.CharField(blank=True, help_text="Job title", max_length=100),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("demo_request", "Demo Request"),
                            ("contact", "Contact Form"),
                            ("event", "Event"),
                            ("referral", "Referral"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="website",
                        help_text="Lead source",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("disqualified", "Disqualified"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="Lead status",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                (
                    "utm_source",
                    models.CharField(
                        blank=True,
                        help_text="UTM source (e.g., google, linkedin)",
                        max_length=100,
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True,
                        help_text="UTM medium (e.g., cpc, email)",
                        max_length=100,
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, help_text="UTM campaign name", max_length=100
                    ),
                ),
                (
                    "utm_term",
                    models.CharField(
                        blank=True,
                        help_text="UTM term (paid search keywords)",
                        max_length=100,
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True, help_text="UTM content (ad variant)", max_length=100
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw form submission data"
                    ),
                ),
                (
                    "next_follow_up",
                    models.DateTimeField(
                        blank=True, help_text="Next follow-up date", null=True
                    ),
                ),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When lead was converted to user",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned sales rep",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "converted_to_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User created from this lead",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="converted_from_lead",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="leads_email_554d9f_idx"),
                    models.Index(
                        fields=["source", "status"], name="leads_source_bba59f_idx"
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="leads_assigne_e66f0c_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="leads_created_e6e479_idx"
                    ),
                ],
            },
        ),
    ]
