# Generated by Django 6.0 on 2025-12-23 14:02

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Organization name", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "uen",
                    models.CharField(
                        help_text="Singapore Unique Entity Number (ACRA)",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_uen",
                                message="Enter a valid Singapore UEN. Valid formats: 12345678A, 123456789A, or T12AB123A.",
                                regex="^[0-9]{8}[A-Z]$|^[0-9]{9}[A-Z]$|^[TSRQ][0-9]{2}[A-Z0-9]{4}[0-9]{3}[A-Z]$",
                            )
                        ],
                    ),
                ),
                (
                    "is_gst_registered",
                    models.BooleanField(
                        default=False,
                        help_text="Whether organization is GST registered",
                    ),
                ),
                (
                    "gst_reg_no",
                    models.CharField(
                        blank=True,
                        help_text="GST Registration Number (IRAS format: M12345678A)",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_gst_registration",
                                message="Enter a valid GST registration number. Format: M12345678A.",
                                regex="^M[0-9]{8}[A-Z]$",
                            )
                        ],
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, help_text="Stripe customer ID", max_length=255
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        help_text="Email for billing notifications", max_length=254
                    ),
                ),
                (
                    "billing_phone",
                    models.CharField(
                        blank=True, help_text="Phone for billing contact", max_length=20
                    ),
                ),
                (
                    "billing_address",
                    models.JSONField(
                        blank=True, default=dict, help_text="Billing address as JSON"
                    ),
                ),
                (
                    "org_timezone",
                    models.CharField(
                        db_column="timezone",
                        default="Asia/Singapore",
                        help_text="Organization timezone",
                        max_length=50,
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en-SG",
                        help_text="Locale for formatting",
                        max_length=10,
                    ),
                ),
                (
                    "org_settings",
                    models.JSONField(
                        blank=True,
                        db_column="settings",
                        default=dict,
                        help_text="Organization settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, help_text="When trial period ends", null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Organization owner",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Additional permissions beyond role",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
                "db_table": "organization_memberships",
                "ordering": ["-joined_at"],
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                help_text="Organization members",
                related_name="organizations",
                through="organizations.OrganizationMembership",
                through_fields=("organization", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["uen"], name="organizatio_uen_7f4024_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="organizatio_slug_5b8b37_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["owner"], name="organizatio_owner_i_0051c7_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["created_at"], name="organizatio_created_8a4b5e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_gst_registered", False),
                    ("gst_reg_no__isnull", False),
                    _connector="OR",
                ),
                name="valid_gst_registration",
            ),
        ),
    ]
